// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionPlanner.Infrastructure.Data;

#nullable disable

namespace SessionPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426035233_AddIdentitySchema")]
    partial class AddIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PersonnelId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.EquipmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultAccessories")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EquipmentModels");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.ConfigurationOS", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OSId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigurationId", "OSId");

                    b.HasIndex("OSId");

                    b.ToTable("ConfigurationOSes");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseConfiguration", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "ConfigurationId");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("CourseConfigurations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseEquipmentModel", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "EquipmentModelId");

                    b.HasIndex("EquipmentModelId");

                    b.ToTable("CourseEquipmentModels");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseLaboratory", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "LaboratoryId");

                    b.HasIndex("LaboratoryId");

                    b.ToTable("CourseLaboratories");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CoursePersonnel", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "PersonnelId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("CoursePersonnels");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CoursePhysicalServer", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalServerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "PhysicalServerId");

                    b.HasIndex("PhysicalServerId");

                    b.ToTable("CoursePhysicalServers");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseSaaSProduct", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaaSProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "SaaSProductId");

                    b.HasIndex("SaaSProductId");

                    b.ToTable("CourseSaaSProducts");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseSoftware", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "SoftwareId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("CourseSoftwares");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseSoftwareVersion", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftwareVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "SoftwareVersionId");

                    b.HasIndex("SoftwareVersionId");

                    b.ToTable("CourseSoftwareVersions");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseVirtualMachine", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VirtualMachineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "VirtualMachineId");

                    b.HasIndex("VirtualMachineId");

                    b.ToTable("CourseVirtualMachines");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.LaboratoryConfiguration", b =>
                {
                    b.Property<int>("LaboratoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LaboratoryId", "ConfigurationId");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("LaboratoryConfigurations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.LaboratorySoftware", b =>
                {
                    b.Property<int>("LaboratoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LaboratoryId", "SoftwareId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("LaboratorySoftwares");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.SessionCourse", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("SessionCourses");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPCs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Laboratories");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.OS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Function")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.PhysicalServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OSId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RamGb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageGb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OSId");

                    b.ToTable("PhysicalServers");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.SaaSProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfAccounts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SaaSProducts");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallCommand")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.SoftwareVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallationDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OsId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SoftwareVersions");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.TeachingNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalComments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AllowsUpdates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredModifications")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpectedStudents")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FoundAllCourses")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasTechNeeds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFastTrack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("SessionId");

                    b.ToTable("TeachingNeeds");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.TeachingNeedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OSId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoftwareVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeachingNeedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OSId");

                    b.HasIndex("SoftwareId");

                    b.HasIndex("SoftwareVersionId");

                    b.HasIndex("TeachingNeedId");

                    b.ToTable("TeachingNeedItems");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.VirtualMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HostServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OSId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RamGb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageGb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HostServerId");

                    b.HasIndex("OSId");

                    b.ToTable("VirtualMachines");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Workstation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OSId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LaboratoryId");

                    b.HasIndex("OSId");

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.AppUser", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Personnel", "Personnel")
                        .WithOne("User")
                        .HasForeignKey("SessionPlanner.Core.Entities.AppUser", "PersonnelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.AppUserRole", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.AppRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.AppUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.ConfigurationOS", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Configuration", "Configuration")
                        .WithMany("ConfigurationOSes")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("ConfigurationOSes")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("OS");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseConfiguration", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Configuration", "Configuration")
                        .WithMany("CourseConfigurations")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseConfigurations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseEquipmentModel", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseEquipmentModels")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.EquipmentModel", "EquipmentModel")
                        .WithMany("CourseEquipmentModels")
                        .HasForeignKey("EquipmentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("EquipmentModel");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseLaboratory", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseLaboratories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Laboratory", "Laboratory")
                        .WithMany("CourseLaboratories")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Laboratory");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CoursePersonnel", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CoursePersonnels")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Personnel", "Personnel")
                        .WithMany("CoursePersonnels")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CoursePhysicalServer", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CoursePhysicalServers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.PhysicalServer", "PhysicalServer")
                        .WithMany("CoursePhysicalServers")
                        .HasForeignKey("PhysicalServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PhysicalServer");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseSaaSProduct", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseSaaSProducts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.SaaSProduct", "SaaSProduct")
                        .WithMany("CourseSaaSProducts")
                        .HasForeignKey("SaaSProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("SaaSProduct");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseSoftware", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseSoftwares")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany("CourseSoftwares")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseSoftwareVersion", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.SoftwareVersion", "SoftwareVersion")
                        .WithMany()
                        .HasForeignKey("SoftwareVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("SoftwareVersion");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseVirtualMachine", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseVirtualMachines")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany("CourseVirtualMachines")
                        .HasForeignKey("VirtualMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.LaboratoryConfiguration", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Configuration", "Configuration")
                        .WithMany("LaboratoryConfigurations")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Laboratory", "Laboratory")
                        .WithMany("LaboratoryConfigurations")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Laboratory");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.LaboratorySoftware", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Laboratory", "Laboratory")
                        .WithMany("LaboratorySoftwares")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany("LaboratorySoftwares")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratory");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.SessionCourse", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("SessionCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Session", "Session")
                        .WithMany("SessionCourses")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.PhysicalServer", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("PhysicalServers")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OS");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Session", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.SoftwareVersion", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("SoftwareVersions")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany("SoftwareVersions")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OS");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.TeachingNeed", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("TeachingNeeds")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Personnel", "Personnel")
                        .WithMany("TeachingNeeds")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.AppUser", "ReviewedByUser")
                        .WithMany("ReviewedTeachingNeeds")
                        .HasForeignKey("ReviewedByUserId");

                    b.HasOne("SessionPlanner.Core.Entities.Session", "Session")
                        .WithMany("TeachingNeeds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Personnel");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.TeachingNeedItem", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany()
                        .HasForeignKey("OSId");

                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId");

                    b.HasOne("SessionPlanner.Core.Entities.SoftwareVersion", "SoftwareVersion")
                        .WithMany()
                        .HasForeignKey("SoftwareVersionId");

                    b.HasOne("SessionPlanner.Core.Entities.TeachingNeed", "TeachingNeed")
                        .WithMany("Items")
                        .HasForeignKey("TeachingNeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OS");

                    b.Navigation("Software");

                    b.Navigation("SoftwareVersion");

                    b.Navigation("TeachingNeed");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.VirtualMachine", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.PhysicalServer", "HostServer")
                        .WithMany("HostedVirtualMachines")
                        .HasForeignKey("HostServerId");

                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("VirtualMachines")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostServer");

                    b.Navigation("OS");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Workstation", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Laboratory", "Laboratory")
                        .WithMany("Workstations")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("Workstations")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratory");

                    b.Navigation("OS");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewedTeachingNeeds");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Configuration", b =>
                {
                    b.Navigation("ConfigurationOSes");

                    b.Navigation("CourseConfigurations");

                    b.Navigation("LaboratoryConfigurations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Course", b =>
                {
                    b.Navigation("CourseConfigurations");

                    b.Navigation("CourseEquipmentModels");

                    b.Navigation("CourseLaboratories");

                    b.Navigation("CoursePersonnels");

                    b.Navigation("CoursePhysicalServers");

                    b.Navigation("CourseSaaSProducts");

                    b.Navigation("CourseSoftwares");

                    b.Navigation("CourseVirtualMachines");

                    b.Navigation("SessionCourses");

                    b.Navigation("TeachingNeeds");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.EquipmentModel", b =>
                {
                    b.Navigation("CourseEquipmentModels");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Laboratory", b =>
                {
                    b.Navigation("CourseLaboratories");

                    b.Navigation("LaboratoryConfigurations");

                    b.Navigation("LaboratorySoftwares");

                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.OS", b =>
                {
                    b.Navigation("ConfigurationOSes");

                    b.Navigation("PhysicalServers");

                    b.Navigation("SoftwareVersions");

                    b.Navigation("VirtualMachines");

                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Personnel", b =>
                {
                    b.Navigation("CoursePersonnels");

                    b.Navigation("TeachingNeeds");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.PhysicalServer", b =>
                {
                    b.Navigation("CoursePhysicalServers");

                    b.Navigation("HostedVirtualMachines");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.SaaSProduct", b =>
                {
                    b.Navigation("CourseSaaSProducts");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Session", b =>
                {
                    b.Navigation("SessionCourses");

                    b.Navigation("TeachingNeeds");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Software", b =>
                {
                    b.Navigation("CourseSoftwares");

                    b.Navigation("LaboratorySoftwares");

                    b.Navigation("SoftwareVersions");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.TeachingNeed", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.VirtualMachine", b =>
                {
                    b.Navigation("CourseVirtualMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
