// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionPlanner.Infrastructure.Data;

#nullable disable

namespace SessionPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317225201_AddSurveyFieldsToNeedAndItem")]
    partial class AddSurveyFieldsToNeedAndItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SessionPlanner.Core.Entities.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.EquipmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultAccessories")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EquipmentModels");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.ConfigurationOS", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OSId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigurationId", "OSId");

                    b.HasIndex("OSId");

                    b.ToTable("ConfigurationOS");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseConfiguration", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "ConfigurationId");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("CourseConfiguration");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseEquipmentModel", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "EquipmentModelId");

                    b.HasIndex("EquipmentModelId");

                    b.ToTable("CourseEquipmentModel");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseLaboratory", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "LaboratoryId");

                    b.HasIndex("LaboratoryId");

                    b.ToTable("CourseLaboratory");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CoursePersonnel", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "PersonnelId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("CoursePersonnel");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CoursePhysicalServer", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhysicalServerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "PhysicalServerId");

                    b.HasIndex("PhysicalServerId");

                    b.ToTable("CoursePhysicalServer");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseSaaSProduct", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaaSProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "SaaSProductId");

                    b.HasIndex("SaaSProductId");

                    b.ToTable("CourseSaaSProduct");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseSoftware", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "SoftwareId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("CourseSoftware");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseVirtualMachine", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VirtualMachineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "VirtualMachineId");

                    b.HasIndex("VirtualMachineId");

                    b.ToTable("CourseVirtualMachine");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.LaboratoryConfiguration", b =>
                {
                    b.Property<int>("LaboratoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LaboratoryId", "ConfigurationId");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("LaboratoryConfiguration");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.PhysicalServerConfiguration", b =>
                {
                    b.Property<int>("PhysicalServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhysicalServerId", "ConfigurationId");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("PhysicalServerConfiguration");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.PhysicalServerSoftware", b =>
                {
                    b.Property<int>("PhysicalServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhysicalServerId", "SoftwareId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("PhysicalServerSoftware");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Permission")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.SoftwareOS", b =>
                {
                    b.Property<int>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OSId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SoftwareId", "OSId");

                    b.HasIndex("OSId");

                    b.ToTable("SoftwareOS");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.VirtualMachineConfiguration", b =>
                {
                    b.Property<int>("VirtualMachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VirtualMachineId", "ConfigurationId");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("VirtualMachineConfiguration");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.VirtualMachineSoftware", b =>
                {
                    b.Property<int>("VirtualMachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VirtualMachineId", "SoftwareId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("VirtualMachineSoftware");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.WorkstationSoftware", b =>
                {
                    b.Property<int>("WorkstationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkstationId", "SoftwareId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("WorkstationSoftware");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPCs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Laboratories");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.OS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Function")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.PhysicalServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OSId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RamGb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageGb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OSId");

                    b.ToTable("PhysicalServers");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.SaaSProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfAccounts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SaaSProducts");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallCommand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.SoftwareVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallationDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OsId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SoftwareVersions");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.TeachingNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AllowsUpdates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredModifications")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpectedStudents")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("FoundAllCourses")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasTechNeeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("SessionId");

                    b.ToTable("TeachingNeeds");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.TeachingNeedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OSId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoftwareId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoftwareVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeachingNeedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OSId");

                    b.HasIndex("SoftwareId");

                    b.HasIndex("SoftwareVersionId");

                    b.HasIndex("TeachingNeedId");

                    b.ToTable("TeachingNeedItems");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.VirtualMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HostServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OSId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RamGb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageGb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HostServerId");

                    b.HasIndex("OSId");

                    b.ToTable("VirtualMachines");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Workstation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OSId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LaboratoryId");

                    b.HasIndex("OSId");

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.ConfigurationOS", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Configuration", "Configuration")
                        .WithMany("ConfigurationOSes")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("ConfigurationOSes")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("OS");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseConfiguration", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Configuration", "Configuration")
                        .WithMany("CourseConfigurations")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseConfigurations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseEquipmentModel", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseEquipmentModels")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.EquipmentModel", "EquipmentModel")
                        .WithMany("CourseEquipmentModels")
                        .HasForeignKey("EquipmentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("EquipmentModel");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseLaboratory", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseLaboratories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Laboratory", "Laboratory")
                        .WithMany("CourseLaboratories")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Laboratory");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CoursePersonnel", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CoursePersonnels")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Personnel", "Personnel")
                        .WithMany("CoursePersonnels")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CoursePhysicalServer", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CoursePhysicalServers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.PhysicalServer", "PhysicalServer")
                        .WithMany("CoursePhysicalServers")
                        .HasForeignKey("PhysicalServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PhysicalServer");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseSaaSProduct", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseSaaSProducts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.SaaSProduct", "SaaSProduct")
                        .WithMany("CourseSaaSProducts")
                        .HasForeignKey("SaaSProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("SaaSProduct");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseSoftware", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseSoftwares")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany("CourseSoftwares")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.CourseVirtualMachine", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("CourseVirtualMachines")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany("CourseVirtualMachines")
                        .HasForeignKey("VirtualMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.LaboratoryConfiguration", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Configuration", "Configuration")
                        .WithMany("LaboratoryConfigurations")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Laboratory", "Laboratory")
                        .WithMany("LaboratoryConfigurations")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Laboratory");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.PhysicalServerConfiguration", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Configuration", "Configuration")
                        .WithMany("PhysicalServerConfigurations")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.PhysicalServer", "PhysicalServer")
                        .WithMany("PhysicalServerConfigurations")
                        .HasForeignKey("PhysicalServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("PhysicalServer");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.PhysicalServerSoftware", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.PhysicalServer", "PhysicalServer")
                        .WithMany("PhysicalServerSoftwares")
                        .HasForeignKey("PhysicalServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany("PhysicalServerSoftwares")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhysicalServer");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.RolePermission", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.SoftwareOS", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("SoftwareOSes")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany("SoftwareOSes")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OS");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.UserPermission", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.UserRole", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.VirtualMachineConfiguration", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Configuration", "Configuration")
                        .WithMany("VirtualMachineConfigurations")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany("VirtualMachineConfigurations")
                        .HasForeignKey("VirtualMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.VirtualMachineSoftware", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany("VirtualMachineSoftwares")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany("VirtualMachineSoftwares")
                        .HasForeignKey("VirtualMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Joins.WorkstationSoftware", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany("WorkstationSoftwares")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Workstation", "Workstation")
                        .WithMany("WorkstationSoftwares")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.PhysicalServer", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("PhysicalServers")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OS");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Session", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.SoftwareVersion", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("SoftwareVersions")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany("SoftwareVersions")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OS");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.TeachingNeed", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Course", "Course")
                        .WithMany("TeachingNeeds")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.Personnel", "Personnel")
                        .WithMany("TeachingNeeds")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.User", "ReviewedByUser")
                        .WithMany("ReviewedTeachingNeeds")
                        .HasForeignKey("ReviewedByUserId");

                    b.HasOne("SessionPlanner.Core.Entities.Session", "Session")
                        .WithMany("TeachingNeeds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Personnel");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.TeachingNeedItem", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany()
                        .HasForeignKey("OSId");

                    b.HasOne("SessionPlanner.Core.Entities.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId");

                    b.HasOne("SessionPlanner.Core.Entities.SoftwareVersion", "SoftwareVersion")
                        .WithMany()
                        .HasForeignKey("SoftwareVersionId");

                    b.HasOne("SessionPlanner.Core.Entities.TeachingNeed", "TeachingNeed")
                        .WithMany("Items")
                        .HasForeignKey("TeachingNeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OS");

                    b.Navigation("Software");

                    b.Navigation("SoftwareVersion");

                    b.Navigation("TeachingNeed");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.User", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Personnel", "Personnel")
                        .WithOne("User")
                        .HasForeignKey("SessionPlanner.Core.Entities.User", "PersonnelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.VirtualMachine", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.PhysicalServer", "HostServer")
                        .WithMany("HostedVirtualMachines")
                        .HasForeignKey("HostServerId");

                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("VirtualMachines")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostServer");

                    b.Navigation("OS");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Workstation", b =>
                {
                    b.HasOne("SessionPlanner.Core.Entities.Laboratory", "Laboratory")
                        .WithMany("Workstations")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionPlanner.Core.Entities.OS", "OS")
                        .WithMany("Workstations")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratory");

                    b.Navigation("OS");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Configuration", b =>
                {
                    b.Navigation("ConfigurationOSes");

                    b.Navigation("CourseConfigurations");

                    b.Navigation("LaboratoryConfigurations");

                    b.Navigation("PhysicalServerConfigurations");

                    b.Navigation("VirtualMachineConfigurations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Course", b =>
                {
                    b.Navigation("CourseConfigurations");

                    b.Navigation("CourseEquipmentModels");

                    b.Navigation("CourseLaboratories");

                    b.Navigation("CoursePersonnels");

                    b.Navigation("CoursePhysicalServers");

                    b.Navigation("CourseSaaSProducts");

                    b.Navigation("CourseSoftwares");

                    b.Navigation("CourseVirtualMachines");

                    b.Navigation("TeachingNeeds");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.EquipmentModel", b =>
                {
                    b.Navigation("CourseEquipmentModels");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Laboratory", b =>
                {
                    b.Navigation("CourseLaboratories");

                    b.Navigation("LaboratoryConfigurations");

                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.OS", b =>
                {
                    b.Navigation("ConfigurationOSes");

                    b.Navigation("PhysicalServers");

                    b.Navigation("SoftwareOSes");

                    b.Navigation("SoftwareVersions");

                    b.Navigation("VirtualMachines");

                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Personnel", b =>
                {
                    b.Navigation("CoursePersonnels");

                    b.Navigation("TeachingNeeds");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.PhysicalServer", b =>
                {
                    b.Navigation("CoursePhysicalServers");

                    b.Navigation("HostedVirtualMachines");

                    b.Navigation("PhysicalServerConfigurations");

                    b.Navigation("PhysicalServerSoftwares");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.SaaSProduct", b =>
                {
                    b.Navigation("CourseSaaSProducts");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Session", b =>
                {
                    b.Navigation("TeachingNeeds");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Software", b =>
                {
                    b.Navigation("CourseSoftwares");

                    b.Navigation("PhysicalServerSoftwares");

                    b.Navigation("SoftwareOSes");

                    b.Navigation("SoftwareVersions");

                    b.Navigation("VirtualMachineSoftwares");

                    b.Navigation("WorkstationSoftwares");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.TeachingNeed", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewedTeachingNeeds");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.VirtualMachine", b =>
                {
                    b.Navigation("CourseVirtualMachines");

                    b.Navigation("VirtualMachineConfigurations");

                    b.Navigation("VirtualMachineSoftwares");
                });

            modelBuilder.Entity("SessionPlanner.Core.Entities.Workstation", b =>
                {
                    b.Navigation("WorkstationSoftwares");
                });
#pragma warning restore 612, 618
        }
    }
}
